### ISSUE TITLE
.style.removeAttribute is not a function

### ISSUE THREAD

**Issue by jerodfritz** [igorlino/angular-fancybox-plus#2]
Closing a popup generates this error :
TypeError: content.get(...).style.removeAttribute is not a function
content.get(0).style.removeAttribute('filter');

Can you incorporate this fix into this module : 
https://github.com/nvidoni/fancybox/issues/2

**Comment by igorlino** [comment]
yes sure, thanks for the tip :+1:

**Comment by jeson114** [comment]
+1
It's not merged into the latest release yet
