### ISSUE TITLE
For some reasons the events onStart, onClosed etc are not being triggered

### ISSUE THREAD

**Issue by sushilkg** [igorlino/angular-fancybox-plus#3]
None of these events seem to be triggered:

onStart: function(d){
    console.log('started');
},
    onClosed: function(d){
    console.log('asdf');
},
    onCancel: function(d){
    console.log('wefsd');
},
    onComplete: function(d){
    console.log('asdfxcv');
}

I'm using angular-fancybox-plus ^1.0.3 and fancybox ^2.1.5.

**Comment by igorlino** [comment]
Could you please create an example in Fiddle ?
https://jsfiddle.net/ 

Thanks
